name: "GitHub Tag Releaser"
description: "Create a github release whenever a new git tag gets created"
author: Marco Souza

branding:
  color: blue
  icon: tag

inputs:
  token:
    description: "Github token"
    required: true
  version-file:
    description: "File containing the version number"
    required: true
  title:
    description: "Title of the release"
    required: false

outputs:
  status:
    description: "Status of the action (success/failure)"
  tag:
    description: "Tag name"
  url:
    description: "URL of the created release"

runs:
  using: "node20"
  main: "index.js"
