name: Release Tag validator

on:
  push:
    paths:
      - package.json

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create release from tag
        # uses: marco-souza/tag-release@0.0.1
        uses: ./
        with:
          title: 🚀 Release
          version-file: package.json
          token: ${{ secrets.GITHUB_TOKEN }}
