name: Release Tag validator

on:
  push:
    # paths:
    #   - package.json

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release from tag
        uses: marco-souza/tag-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
