name: Release Tag validator

on:
  push:
    paths:
      - package.json

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release from tag
        uses: ./
        with:
          version-file: package.json
          token: ${{ secrets.GITHUB_TOKEN }}
